
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0

name: Release

jobs:
  # crate_publish:
  #   name: Publish on crates.io
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@v2

  #     - name: Run cargo login
  #       uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
  #       with:
  #         command: login
  #         args: "${{secrets.CARGO_TOKEN}}"
 
  #     - name: Run cargo publish
  #       uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
  #       with:
  #         command: publish

  release_linux:
    name: Release (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo build
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
        with:
          command: build
          args: --all --release

      - name: Strip and rename binary
        run: strip target/release/jwtdecode && mv target/release/jwtdecode target/release/jwtdecode_linux_amd64

      - name: Release
        uses: softprops/action-gh-release@b21b43df682dab285bf5146c1955e7f3560805f8
        with:
          files: |
            target/release/jwtdecode_linux_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release_windows:
    name: Release (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo build
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
        with:
          command: build
          args: --all --release

      - name: Rename binary
        run: ren target/release/jwtdecode.exe jwtdecode_windows_amd64.exe

      - name: Release
        uses: softprops/action-gh-release@b21b43df682dab285bf5146c1955e7f3560805f8
        with:
          files: |
            target/release/jwtdecode_windows_amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release_macos:
    name: Release (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-apple-darwin
          override: true

      - name: Run cargo build
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
        with:
          command: build
          args: --all --release

      - name: Strip and rename binary
        run: strip target/release/jwtdecode && mv target/release/jwtdecode target/release/jwtdecode_macos_amd64

      - name: Release
        uses: softprops/action-gh-release@b21b43df682dab285bf5146c1955e7f3560805f8
        with:
          files: |
            target/release/jwtdecode_macos_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
